### ISSUE TITLE
Lily Texture Packer not working for me

### ISSUE THREAD

**Issue by taserak** [eliemichel/MapsModelsImporter#103]
Not sure if this is the right place for this

I LilyTexturePacker is not working for me.
I get this error:

```
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\LilyTexturePacker\frontend.py", line 44, in execute
    pack_textures(self.getObjects(context), spacing=self.spacing)
  File "C:\Users\adams\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\LilyTexturePacker\packing.py", line 163, in pack_textures
    img.pixels.foreach_get(all_pixels.ravel())
AttributeError: 'bpy_prop_array' object has no attribute 'foreach_get'

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\adams\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\LilyTexturePacker\frontend.py", line 44, in execute
    pack_textures(self.getObjects(context), spacing=self.spacing)
  File "C:\Users\adams\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\LilyTexturePacker\packing.py", line 163, in pack_textures
    img.pixels.foreach_get(all_pixels.ravel())
AttributeError: 'bpy_prop_array' object has no attribute 'foreach_get'

location: <unknown location>:-1

bpy.ops.object.select_all(action='SELECT')
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\LilyTexturePacker\frontend.py", line 44, in execute
    pack_textures(self.getObjects(context), spacing=self.spacing)
  File "C:\Users\adams\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\LilyTexturePacker\packing.py", line 163, in pack_textures
    img.pixels.foreach_get(all_pixels.ravel())
AttributeError: 'bpy_prop_array' object has no attribute 'foreach_get'

location: <unknown location>:-1
```

**Comment by eliemichel** [comment]
Hi @taserak it seems that you are using a version of Blender that is older than 2.83.3. I would suggest to either upgrade Blender (the last LTS works if you want to stay on a 2.83 based version) or if it really isn't possible to downgrade LilyTexturePacker to v1.0.1. It'll be much slower though, as the `foreach_get` function reported missing by your error messages was at the heart of the speed-up of v1.1.0
