### ISSUE TITLE
can't create maps model 

### ISSUE THREAD

**Issue by cuiguangheng** [eliemichel/MapsModelsImporter#107]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file 
[111.zip](https://github.com/eliemichel/MapsModelsImporter/files/5498818/111.zip)

 - Your GPU name  <Intel(R) UHD Graphics 630>
 - Version of this add-on (must be the most recent one) 
 - Version of RenderDoc (1.9 recommended, do not use v1.10)   <v1.9>
 - Version of Blender (2.82 minimum)  <v2.83>

I had try couple times  completely every step as you video teach, but it still doesn't work . Warming message show as below.
**Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps (NOT Google Earth)
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
Console log is accessible in Windows > Toggle System Console (right click to copy).**

**Comment by jokumo** [comment]
I'm having the same issue. To see if it's the same problem can you do the following steps?

- turn on Debug Info [Edit/preferences.../Add-ons/Import-Export: Maps Models Importer --> Checkbox "Debug Info" at the bottom]
- try to load a rdc file
- go to the System Console [Window/Toggle System Console]

Is there a message like:
"ImportError: DLL Load failed:[...]"?

**Comment by cuiguangheng** [comment]
> I'm having the same issue. To see if it's the same problem can you do the following steps?
> 
> * turn on Debug Info [Edit/preferences.../Add-ons/Import-Export: Maps Models Importer --> Checkbox "Debug Info" at the bottom]
> * try to load a rdc file
> * go to the System Console [Window/Toggle System Console]
> 
> Is there a message like:
> "ImportError: DLL Load failed:[...]"?

 Mate , do you have any idea about this issue?

Read prefs: C:\Users\cuigu\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: D:\software\blender\2.83\python
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
google_maps_rd failed and returned:
Loading capture from D:\software\blender\Blender GIS cache\why1.rdc...
Couldn't open file: ReplayStatus.FileIncompatibleVersion
Traceback (most recent call last):
  File "C:\Users\cuigu\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 260, in <module>
    main(controller)
  File "C:\Users\cuigu\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 252, in main
    scraper.run()
  File "C:\Users\cuigu\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 182, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

**Comment by jokumo** [comment]
> Mate , do you have any idea about this issue?
No, not yet. But let's see what else we can do.

I would try to download a sample capture file as described on [blenderartist.org](https://blenderartists.org/t/google-maps-models-importer/1153561/23). This way you can check if it's about your rdc file or if the addon itself does something wrong.

Let us know if you could load the sample capture file.
And if you get different error messages then in the system console the above ones then please post it again here.

**Comment by cuiguangheng** [comment]
My friend, I use the sample but still make no changes in blender, error report as below.

Read prefs: C:\Users\cuigu\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
found bundled python: D:\software\blender\2.83\python
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available

**Comment by jokumo** [comment]
Is Debug Info still turned on? Because now there is are no errors. The lines with BlenderGIS are from another Addon.
I don't know what the sample capture contains, but at least the Addon doesn't run into a error.

**Comment by cuiguangheng** [comment]
Sorry, I capture the wrong message . Console log did not mention anything , but the error still show like this.

Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps (NOT Google Earth)
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
Console log is accessible in Windows > Toggle System Console (right click to copy).
![image](https://user-images.githubusercontent.com/34788169/98514945-3fc8bb00-22a5-11eb-8105-0604dfeb5c00.png)

**Comment by jokumo** [comment]
> Sorry, I capture the wrong message . Console log did not mention anything , but the error still show like this.
All ok, it was the console log that I was looking for. And it does not mention any crash. So it's different with the sample capture. 
I looked at your 111.rdc and it seems to me like there is no 3D Data. That's probably why the addon crashes with additional error messages in the console.
If you load the sample capture.rdc into RenderDoc it looks different than your file. I'm just guessing, but it might need a "target+depth" entry and the drawElements entries should have bigger numbers...
![Screenshot 2020-11-09 104834](https://user-images.githubusercontent.com/16837904/98526069-9d471280-2279-11eb-82eb-5c9b33211b75.png)

So first: Your RDC is not valid. (Addon crashes with a "Couldn't open file: ReplayStatus.FileIncompatibleVersion" in the console)
Second: Even the sample capture.rdc does not work for some reason (but it does not crash the addon, it just terminates with the same error message (altough it's a different error)).

At this moment I have no idea why the sample capture does not load. But I suggest you continue experimenting with the sample capture to make sure the error is not about the rdc file.

**Comment by cuiguangheng** [comment]
Thanks a lot,  I'm gonna to  switch to another computer to make a try ,  let's keep in touch and see what would happen.  Again , thanks a lot for you kindness help.

**Comment by eliemichel** [comment]
(Thanks @jokumo for handling this issue :) )

**Comment by jokumo** [comment]
@cuiguangheng hey, does it work now? I realised that it's unclear what version of RenderDoc was used to capture the sample capture. I made two captures for myself, it might be useful. Remember that AddOn Version 0.3.3 needs RenderDoc 1.10 and Version 0.3.2 and below needs RenderDoc 1.5-1.9
[bridge (RD1.9).rdc](https://drive.google.com/file/d/1kCOloprpufwwHUmFCKZv23maQkz7a9PI/view?usp=sharing)
[bridge (RD1.10).rdc](https://drive.google.com/file/d/1pgA1AQizU9fMLbTzuJbq7G_GHljK1T5D/view?usp=sharing)

In my case I could make it run with Blender 2.83 and MapsModelsImporter 0.3.2 or 0.3.1 
If it works it will need some time to load the capture. Blender might get unresponsive, this is normal.

**Comment by cuiguangheng** [comment]
I'm so sorry about that I haven't take a try yet. Since I'm so busy of my job , I forgot about this . I would try it later and I will let you know dose I can work or not. Again , thanks a lot ,mate.

**Comment by cuiguangheng** [comment]
I'm so sorry about that I haven't take a try yet. Since I'm so busy of my job , I forgot about this . I would try it later and I will let you know dose I can work or not. Again , thanks a lot ,mate.@jokumo

**Comment by cuiguangheng** [comment]
@jokumo My Friend , I had try the file you shared to me . The file bridge(RD1.9) works ,it can import to my Blender.  But things are weird , my Blender add-on and RenderDoc's version  exactly  the same as you told me .   My Blender version is 2.83 . 
----------------------------------------------------------------------------------------------------------------------------------------
File bridge (RD1.9) succeed import to my Blender 
![1 9](https://user-images.githubusercontent.com/34788169/100074130-55c7a580-2e79-11eb-8dc3-bc071c28680c.png)
Add-on & renderdoc version screenshot
![addon](https://user-images.githubusercontent.com/34788169/100073808-ebaf0080-2e78-11eb-8994-5992147b6c2e.png)
![RenderDoc](https://user-images.githubusercontent.com/34788169/100073838-f5386880-2e78-11eb-9188-2c09ebd3e7a5.png)

**Comment by eliemichel** [comment]
I assume this means the whole issue is fixed, right?

**Comment by cuiguangheng** [comment]
> I assume this means the whole issue is fixed, right?

Sorry, I have no idea why the conversation  is closed, but the issue isn’t be fixed yet.

**Comment by jokumo** [comment]
@cuiguangheng The question is: What exactly is the issue. 
- your captured RDC files don't work
  - this is not a MapsModelsImporter-Issue but an Issue with RenderDoc itself. And [RenderDoc](https://github.com/baldurk/renderdoc) is an independent program. I see two possible sources for this problem. 
    - you don't use RenderDoc correctly
      - just keep trying, use the "capture in X seconds"-option, move the 3D model while capturing. Eventually you will figure this out.
    - there's something wrong with RenderDoc
      - search [RenderDocs Issues](https://github.com/baldurk/renderdoc/issues) to see if your problem is already reported
  - since it's not about MapsModelsImporter it would be correct to close this conversation.
- it does not work with Blender 2.90.1 and MapsModelsImporter 0.3.3
  - you could try to install Python on your computer as described [here](https://github.com/eliemichel/MapsModelsImporter/issues/108#issuecomment-735433229)
  - or you keep using version 0.3.2 until version 0.3.4 is published :)

**Comment by eliemichel** [comment]
@cuiguangheng ok sorry, reopenning, but so I am a bit confused about what the current state of your problem is. Could you elaborate?

**Comment by jokumo** [comment]
@cuiguangheng any update on this Issue? Does it still exist with the current version of MapsModelsImporter and a [Sample File](https://github.com/eliemichel/MapsModelsImporter-samples)?

Please remember that RDC-Files and RenderDoc of Version 1.11 and 1.12 do not work with the current version (0.3.5). You need to use sample Files <=1.10.

Would be nice to give us an update to see if we can close this Issue.
