### ISSUE TITLE
"The system cannot find the file specified - location: <unknown location>: -1" when importing RDC

### ISSUE THREAD

**Issue by rhulse-in** [eliemichel/MapsModelsImporter#119]
- The .rdc file
**[indy.rdc](https://www.dropbox.com/s/u2zmuvpesjy321l/Indy.rdc?dl=0)**

 - Your GPU name
**GTX1060**
 
- Version of this add-on (must be the most recent one)
**0.3.3**
 - Version of RenderDoc (1.10 recommended)
**Have tried 1.11, 1.10, and 1.5 - RDC linked was generated from 1.10**  Also tried importing an example .rdc and it failed identically. 

 - Version of Blender (2.82 minimum)
**2.91.0**

The injection process with Chrome seems to work.  The import of rdc in Blender gives this error:

Python: Traceback (most recent call last):
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps.py", line 272, in importCapture
    captureToFiles(context, filepath, prefix, max_blocks)
  File "C:\Users\Ryan\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps.py", line 53, in captureToFiles
    out = subprocess.check_output([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)], stderr=subprocess.STDOUT)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

Similar issues were referenced in issue #25 and #37.   python.exe is in C:\Program Files\Blender Foundation\Bender 2.91\2.91\python\bin\  

python3.dll and python37.dll are in the \Blender 2.91\ directory, but python.exe is not.

**Comment by eliemichel** [comment]
Isn't `python37.dll` in `Bender 2.91\2.91\python\bin\`?
ANyway you should try the new v0.3.5-rc2 released earlier today. It adds an extra dll that is missing on some systems, which is likely the file that is not found in your case.
