### ISSUE TITLE
Cannot import via Blender

### ISSUE THREAD

**Issue by ilusion32** [eliemichel/MapsModelsImporter#120]
Greetings,

I have done this in an older version but now it won't work at all even if I'm following the same steps over and over again. Panning and orbiting camera around the area of interest, generate capture, save and this (on 2.83 version)

Traceback (most recent call last):
  File "C:\Users\VALI-19\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 186, in <module>
    main(controller)
  File "C:\Users\VALI-19\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 82, in main
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

and this (on 2.91 version)

Python: Traceback (most recent call last):
  File "C:\Users\VALI-19\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\VALI-19\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps.py", line 221, in importCapture
    captureToFiles(filepath, prefix, max_blocks)
  File "C:\Users\VALI-19\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps.py", line 51, in captureToFiles
    subprocess.check_output([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)])
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

Plus the conventional warning: 

Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps (NOT Google Earth)
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
Console log is accessible in Windows > Toggle System Console (right click to copy).

I am with google maps active, clicked the 3D view option, disabled labels, pan, orbit, zoom-in/-out. Also, whatever I do, the capture will vary in size (19Mb, 40Mb, now 70Mb). 

https://we.tl/t-ICwU8lTDVp

Attached in link is the file... apparently too big to upload here as zip, because of large amount of 3D mesh.

If you could help, thanks a lot in advance.

**Comment by eliemichel** [comment]
Did you make sure you're using the very last release ([0.3.5](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1)). This looks like the bug that it's fixing.

**Comment by ilusion32** [comment]
Hi and thanks for the fast reply.

Yes, it worked now with this version 0.3.5.

Thanks a lot!
