### ISSUE TITLE
Cannot import RDC file into blender!

### ISSUE THREAD

**Issue by darshandaiv14** [eliemichel/MapsModelsImporter#125]
.rdc file: []https://1drv.ms/u/s!AuGknVooHtMwnA22w3NuCY984KH0
GPU: GeForce RTX 2060 
Render doc version 1.10
add on version: 0.3.5
blender version: 2.91.0
.
While importing rdc file into blender it is showing the following error -
.

Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps.py", line 272, in importCapture
    if uvs and len(uvs[0]) > 2:
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps.py", line 53, in captureToFiles
    MSG_RDMODULE_NOT_FOUND = "Error: Can't find the RenderDoc Module." + MSG_CONSOLE_DEBUG_OUTPUT
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

what should I do to fix this??

**Comment by insanelynotgood** [comment]
MapsModelsImporter does not support render doc version 1.10
Try it with render doc version 1.08

**Comment by eliemichel** [comment]
@insanelynotgood nope, v1.10 is the recommended RenderDoc to go with the version of the add-on they used ([v0.3.5](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1)).

@darshandaiv14 There seems to be a leftover of a previous install, try completely removing the add-on and reinstalling it. In particular, the line quoted in the error message don't match the errors that are raised.
