### ISSUE TITLE
Can't import sample files with correct setup

### ISSUE THREAD

**Issue by jacobLOtt** [eliemichel/MapsModelsImporter#127]
I've tried different combinations of "approved" versions, but keep getting the same error while importing. 

 - The .rdc files: bridge-RD_1.9.rdc, bridge-RD_1.10.rdc, alhambra-RD_1.11.rdc
 - GeForce RTX 3090
 - Version of this add-on: v0.3.5-rc2
 - Version of RenderDoc: 1.10 
 - Version of Blender: 2.90

```
google_maps_rd failed and returned:
Loading capture from D:\rnd\_src\bridge-RD_1.10.rdc...
Couldn't open file: ReplayStatus.FileCorrupted
Traceback (most recent call last):
  File "C:\Users\Jacob\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
    main(controller)
  File "C:\Users\Jacob\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
    scraper.run()
  File "C:\Users\Jacob\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'
```

**Comment by eliemichel** [comment]
Mmh I just checked it is still working for me with the exact same software set-up, so maybe a mismatch in due to your GPU being much newer than the ones used to capture the sample files. Have you try capturing your own file? If so, could you share it?

**Comment by dnebannoS** [comment]
I'm getting pretty much the same error with RenderDoc 1.11 and Blender 2.91 (Plugin version: 0.3.5).
Tested it with my own capture and the Pumpa example, both lead to the same error.

> google_maps_rd failed and returned:
> Loading capture from C:\Users\me\Desktop\blender_terrain_test\from_renderdoc.rdc...
> Couldn't initialise replay: 15
> This is likely due to an unsupported version of RenderDoc.
> Traceback (most recent call last):
>   File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
>     main(controller)
>   File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
>     scraper.run()
>   File "C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
>     drawcalls = controller.GetDrawcalls()
> AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

**Comment by eliemichel** [comment]
Just don't use v1.11, stick to v1.10 as specified in the [release note](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1).
