### ISSUE TITLE
Unable to import - using Blender 2.91.2 / Renderdoc 1.10 and MapsModelImporter 3.5

### ISSUE THREAD

**Issue by simoncb49** [eliemichel/MapsModelsImporter#146]
Hi Elie,
I have tried a variety of options over the last two days none of which seemed to work. My latest attempt was using you recommended Blender 2.91.2 / Renderdoc 1.10 and MapsModelImporter 3.5. It all appeared to work fine See the screenshot of the Renderdoc file. 
![RenderDoc Picture of House for import to blender Screenshot 2021-02-08 100206](https://user-images.githubusercontent.com/74393868/107208100-08c78a00-69f9-11eb-8949-8df00776fcb0.png)
Unfortunately Blender was having none of it :-)
I attach the error report transcription 
[Reported Error with Blender 2.91.2 Renderdoc1.10 and MapsModelImporter3.5.txt](https://github.com/eliemichel/MapsModelsImporter/files/5943019/Reported.Error.with.Blender.2.91.2.Renderdoc1.10.and.MapsModelImporter3.5.txt)
A little lost on what to try next and would really welcome your ideas...I am a total noob to Blender but I have imported the right add on as per your earlier warnings.
Kind Regards,
Simon Blandford
Ps I tried to import the rdc file but even zipped it was over 30 mb.

**Comment by jokumo** [comment]
Try to import a Sample file: [https://github.com/eliemichel/MapsModelsImporter-samples](https://github.com/eliemichel/MapsModelsImporter-samples)

**Comment by simoncb49** [comment]
Hi Jorma,
Yes I tried that with no success.
Kind regards
Simon

**Comment by jokumo** [comment]
Just to make sure, you are on a Windows machine, right?
I just tried with a fresh installation of Blender 2.91.2 and AddOn 0.3.5 and [Manhattan Bridge 1.10](https://github.com/eliemichel/MapsModelsImporter-samples#new-york-manhattan-bridge-110) from the samples, and it worked on my computer.

Another thing you could try is to load the [Alhambra 1.11](https://github.com/eliemichel/MapsModelsImporter-samples#granada-alhambra) sample which should give another Error message with details about the used python and python home directory. Not sure if this helps, but it's worth to try I think.

**Comment by eliemichel** [comment]
Hi @simoncb49 looks like there is a mismatch between the line numbers and error message, try to completely uninstall the addon and reinstall it.

**Comment by simoncb49** [comment]
Hello Elie,
I will try but dont really understand the coding...I am no programmer...
Kind Regards,
Simon

**Comment by eliemichel** [comment]
I really meant uninstall and reinstall the addon as a normal user, nothing related to coding. My remark about line numbers was more to let you know of my reasonning.

**Comment by polygonfuture** [comment]
I am having similar issue with RenderDoc 1.10,  MapsModelImporter latest release (3.5 rc2), and Blender 2.82.

I am attempting to import through Google Earth Web (via chrome browser).  

I get this error:

```
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading. 
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output
```

**Comment by eliemichel** [comment]
With google earth many times the capture does not include 3D info, it is good practice to 1 take a burst of 2-3 captures and check them out to keep only one that in effect as 3D.

**Comment by polygonfuture** [comment]
@eliemichel  The capture definitely contains 3D information. I see it in the list of data captured.

Would you be able to verify a working google earth capture on your end and push the  rdc to your repo of samples?

**Comment by jokumo** [comment]
@polygonfuture I take this to a new Issue with a more specific title. Let's continue there: [Importing RDC from Google Earth (partially) fails](https://github.com/eliemichel/MapsModelsImporter/issues/151)

The Issue of this threat is something else, since the author can't import any sample files.

**Comment by hu277** [comment]
With the above mentioned configuration i get the following import error with the sample rdc objects:
==========================================================================================
google_maps_rd failed and returned:
Loading capture from F:\Customscenery\Bilder\bridge-RD_1.10.rdc...
Couldn't open file: ReplayStatus.FileCorrupted
Traceback (most recent call last):
  File "C:\Users\Uwe\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
    main(controller)
  File "C:\Users\Uwe\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
    scraper.run()
  File "C:\Users\Uwe\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

No one of the samples work

**Comment by simoncb49** [comment]
Hi Elie,
Could you be precise about which copies of Blender, Render Doc and Maps
Modeeler work together. I have uninstalled and reinstalled a variety of
options but none seem to work.
