### ISSUE TITLE
Error on Importing RDC Files

### ISSUE THREAD

**Issue by tarikpranto** [eliemichel/MapsModelsImporter#157]
Python: Traceback (most recent call last):
  File "C:\Users\Md. Tarik Pranto\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\Md. Tarik Pranto\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps.py", line 272, in importCapture
    if uvs and len(uvs[0]) > 2:
  File "C:\Users\Md. Tarik Pranto\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps.py", line 53, in captureToFiles
    MSG_RDMODULE_NOT_FOUND = "Error: Can't find the RenderDoc Module." + MSG_CONSOLE_DEBUG_OUTPUT
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

![Screenshot (2)](https://user-images.githubusercontent.com/63959319/113090394-7d55c280-920b-11eb-8bff-b4024fc9d253.png)
![Screenshot (1)](https://user-images.githubusercontent.com/63959319/113090418-85adfd80-920b-11eb-95c3-b6f9cde890de.png)

Render Doc Version 1.10
Blender-2.92.0-windows64
CPU - Ryzen 3 3200G (Built in Graphics)

Please Help!!

**Comment by leotropicae** [comment]
I'm having the same problem so I tried many things, installing different Renderdoc versions and different Add-on versions.
I am able to create a .rdc file but it does not open on Blender so I downloaded the sample files and tested all of them, none opens. I'm with the following setup:

Blender 2.92
Render Doc 1.10
MapsModelsImporter 3.6 (I also tried to add the 3.2 but it ddoesn't install it for some reason)
What I'm doing wrong?

**Comment by eliemichel** [comment]
Check out [v0.3.7](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.7)
