### ISSUE TITLE
Cannot import RDC file - WinError 87

### ISSUE THREAD

**Issue by oggy1189** [eliemichel/MapsModelsImporter#180]
Hello, if anyone can help please do as I've tried everything I can think of and am at a total dead end.

I'm able to generate the RDC file without trouble but whenever I try to import, Blender is having none of it and keep getting the WinError 87 error. I've tried the following to fix the issue (I should point out that I'm not a programmer and my understanding of coding is virtually non-existent):

- Tried every version of the addon from 0.3.0 up, each time with the versions of Blender and RenderDoc specified plus some other combos people have said worked for them. Same error every time.
- Tried with sample RDC files provided. Again, same error.
- Using a PYTHONPATH environment variable set to version of Python used in Blender and RenderDoc, and a standalone python install. Blender just ignores this...
- Also using the RENDERDOC_PYTHON_PREFIX64 with each of the above python versions (saw it on the RenderDoc python documentation but again, I'm not a programmer so may not be relevant)

If anyone can help me fix this would be a massive help! I'll post the RDC file along with the error and some screenshots of the results of some import requests in the scripting console (basically looked at every forum response I could find on the issue and saw this requested a few times but was never given). Thanks in advanced 👍

 - Files - https://u.pcloud.link/publink/show?code=kZFblCXZoPBxu1etuukcuFNs85a58jdLJYrk (for whatever reason, Github won't let me upload anything, even allowed files so I'm having to do it this way 🤦‍♂️🤦‍♂️🤦‍♂️)
 - GPU - GTX 780 TI
 - MapsModelsImporter-0.4.1-rc1
 - Blender 2.93.1
 - RenderDoc 1.13

**Comment by eliemichel** [comment]
Hi @oggy1189, thanks for having tried hard before reporting here.
Did you try installing vc_redist.x64? https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by oggy1189** [comment]
> Hi @oggy1189, thanks for having tried hard before reporting here.
> Did you try installing vc_redist.x64? https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Hi, just installed it and tried again. Same error

Python: Traceback (most recent call last):
  File "C:\Users\luke\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\luke\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\google_maps.py", line 307, in importCapture
    captureToFiles(context, filepath, prefix, max_blocks)
  File "C:\Users\luke\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\google_maps.py", line 79, in captureToFiles
    out = subprocess.check_output([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)], stderr=subprocess.STDOUT, text=True)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 87] The parameter is incorrect

location: <unknown location>:-1

**Comment by eliemichel** [comment]
Try the incoming 0.4.1: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.4.1-rc1

In Blender's Python console do the following and copy the output here:

```python
import sys
print(sys.executable)
```

Check that the file C:\Users\luke\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\google_maps_rd.py exists.

Put the capture file in at a path with no special character in directory names.

**Comment by oggy1189** [comment]
That's the version I was using 👌

Python response = C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE

Yes the file is there 
![Untitled](https://user-images.githubusercontent.com/87746694/126979883-48badaa4-fdd2-4f56-afda-84dcc4d081bb.jpg)

And have placed on the desktop.

Let me know if you need anything else 👍

**Comment by eliemichel** [comment]
Okey in the same console now try:

```python
filepath = "THE/PATH/TO/YOUR/CAPTURE.rdc"
import subprocess
import os
subprocess.check_output([
  r"C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE",
  r"C:\Users\luke\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MapsModelsImporter\google_maps_rd.py",
  filepath,
  os.path.dirname(filepath),
  "-1"
], stderr=subprocess.STDOUT)
```

(I hope I did not make a typo I did not test the script)

**Comment by oggy1189** [comment]
Sorry, deleted the last one as wanted to check something. 

Kinda weird, when I paste the code as your wrote it it comes in fine
![001](https://user-images.githubusercontent.com/87746694/127006741-4b1200e2-9ecc-433b-832b-6dc64ed01aac.jpg)

...yet when I alter the path section I get a syntax error
![002](https://user-images.githubusercontent.com/87746694/127007368-aeed5911-1d08-443a-ad6e-1ca88593bbcc.jpg)

I've tried pasting the full address and also inverted the dashes just to be sure and it's the same each time. Apologies for sucking at coding lol

**Comment by eliemichel** [comment]
Mmh it may come from antoher of your add-ons, try disabling all of them (see #149)

**Comment by oggy1189** [comment]
Just tried, no luck. Same win87 error

**Comment by eliemichel** [comment]
Are you able to run "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\bin\python.EXE" at all? You can try Win+E, then paste this, with quotes around, it should start a Python console.

**Comment by oggy1189** [comment]
Yep, opens it fine
![Untitled](https://user-images.githubusercontent.com/87746694/127217032-119ad394-7591-448c-854f-476dd2b0b768.jpg)

**Comment by eliemichel** [comment]
I'm sorry this is a tough one... I really don't get why subprocess fails at spawning this python.exe then.
Could you try the same lines of code I had you run in Blender's console but this time in that console you got in the last test?

**Comment by oggy1189** [comment]
Just tried and it's giving the same error 😔

![001](https://user-images.githubusercontent.com/87746694/127226480-97c46e07-5984-4b50-8d8a-0619defe569d.jpg)

Out of curiosity I tried running it on a standalone install of python 3.9.2. It gave the Win87 error but with different file locations. Don't know if that gives any clues but I'll include as well.

![002](https://user-images.githubusercontent.com/87746694/127226695-303dab38-616a-49d3-90c7-f6f34267400c.jpg)

**Comment by eliemichel** [comment]
@KJJohnson37 The last version of the addon is for Blender 2.93, because 2.92 used a different version of Python. The last version that supports 2.92 is [v0.3.7](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.7). You must use RenderDoc 1.10 if you use this version of the add-on.

@oggy1189 Really I don't know, sorry, the error is beyond the scope of this very add-on I fear.

**Comment by LudoGH** [comment]
@Eliemichel thanks for your amazing plugin.
I had the exact same WinError 87, strange location error. (Win10/RenderDoc1.13/MMIv0.4.1/Blender v3.0.1/SacreCoeur).
=> It turned out, this was my **COMODO Antivirus software.**
I disabled its Antivirus/AutoContainment/VirusScope features just during the .rdc import in Blender => **Problem SOLVED**.
