### ISSUE TITLE
Blender-2.82 support

### ISSUE THREAD

**Issue by brothermechanic** [eliemichel/MapsModelsImporter#19]
I get this error on importing rdc file
```
Traceback (most recent call last):
  File "/home/bm/.config/blender/2.82/scripts/addons/MapsModelsImporter/operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "/home/bm/.config/blender/2.82/scripts/addons/MapsModelsImporter/google_maps.py", line 180, in importCapture
    captureToFiles(filepath, prefix)
  File "/home/bm/.config/blender/2.82/scripts/addons/MapsModelsImporter/google_maps.py", line 36, in captureToFiles
    blender_version = [d for d in os.listdir(blender_dir) if d.startswith("2.")][0]
IndexError: list index out of range

location: <unknown location>:-1
```

**Comment by eliemichel** [comment]
This is surprising, does Blender 2.82 change the directory layout of a typical Blender installation? According to your error message, the script could not find the folder "2.82" that should be next to blender.exe.
