### ISSUE TITLE
How to get own bin renderdoc libs?

### ISSUE THREAD

**Issue by brothermechanic** [eliemichel/MapsModelsImporter#20]
Hello
There are renderdoc.pyd and renderdoc.dll bin files
Please, help me. How to compile them?

**Comment by brothermechanic** [comment]
Hello agane
I copy libs 
from http://security.ubuntu.com/ubuntu/pool/universe/r/renderdoc/renderdoc_1.6+dfsg-1build1_amd64.deb 
to /home/bm/.config/blender/2.82/scripts/addons/MapsModelsImporter/bin/linux64/ dir 

There are librenderdoc.so  renderdoc.so  TODO

But dont work for me
2.82 https://github.com/eliemichel/MapsModelsImporter/issues/19
2.80 
```
Loading capture from /home/bm/Sync/rd/16.rdc...
Traceback (most recent call last):
  File "/home/bm/.config/blender/2.80/scripts/addons/MapsModelsImporter/google_maps_rd.py", line 170, in <module>
    with CaptureWrapper(CAPTURE_FILE) as controller:
  File "/home/bm/.config/blender/2.80/scripts/addons/MapsModelsImporter/rdutils.py", line 45, in __enter__
    status,self.controller = self.cap.OpenCapture(None)
TypeError: CaptureFile_OpenCapture expected 2 arguments, got 1
Saved session recovery to '/tmp/quit.blend'

```

**Comment by eliemichel** [comment]
Hi @brothermechanic ! Good question.

Two things: first the dll/so included in RenderDoc releases misses (or missed at the time) some elements for the Python API. Secondly, for this to work with Blender, it must use the very same version of Python. For these two reasons, you cannot simply take the dll/so and pyd files from a release tarball of RenderDoc, you'll have to build them from source. ensuring you drop the right version of Python and enable the Python API. Let me know is you attempted so.

Also, unfortunately even though I had planned on releasing this on linux as well, turns out that RenderDoc misses the "Inject into process" feature on linux so it would only work for importing rdc files, not for capturing them.

**Comment by brothermechanic** [comment]
Hello
Yes, you are right
I will try to compile renderdoc's libs by myself
I will post comment about any news
