### ISSUE TITLE
problems while importing in blender

### ISSUE THREAD

**Issue by bydoodle** [eliemichel/MapsModelsImporter#229]
Hello, i'd try to import rdc file but blender messaging me an error
![Знімок екрана (2)](https://user-images.githubusercontent.com/82917218/176971287-90e9ac96-ca4d-46e5-8309-041cc6f1a270.png)

**Comment by dcnkkcn** [comment]
Helo buddy 
This is the same issue in my case plz help me

**Comment by DavidPulcifer** [comment]
Having the same issue. Running Blender 3.1.0. Tried importing the Cape Town Map and got this error:

Python: Traceback (most recent call last):
  File "C:\Users\(censored)\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\(censored)\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MapsModelsImporter\google_maps.py", line 305, in importCapture
    
  File "C:\Users\(censored)\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MapsModelsImporter\google_maps.py", line 80, in captureToFiles
    os.environ["PATH"] += os.pathsep + os.path.join(python_home, "bin")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 23661: invalid start byte

location: <unknown location>:-1

**Comment by matteo-chevalier** [comment]
Hey I have the same problem, I cannot import RDC to blender 

I tried several version of renderdoc and the older are not compatible with the recent chrome version

I tried different sample from GitHub and they work.

What to do ?

**Comment by saiidabs** [comment]
same problem , i tried using my captures and no luck , so then i used the sample ones  [in this repo sample list](https://github.com/eliemichel/MapsModelsImporter-samples) and still no luck , these are more following configurations: 
-  blender 3.3.0
- renderDoc v1.22
- Maps Models Importer v0.5.0

**Comment by Ruveen2001** [comment]
> Hello, i'd try to import rdc file but blender messaging me an error ![Знімок екрана (2)](https://user-images.githubusercontent.com/82917218/176971287-90e9ac96-ca4d-46e5-8309-041cc6f1a270.png)

I've had the same error, tried importing the Cape Town sample and the same error showed up. I used RenderDoc v1.10, MapsModelsImporter-v0.3.3 and the newest Blender, so I'm not sure what the issue is. (The RenderDoc and MapsModelsImporter versions work together, since I used the same versions that a tutorial video suggested.
![image](https://user-images.githubusercontent.com/76436352/209255863-240613d7-08ba-4bad-87be-a57cecc5d74f.png)

**Comment by Ruveen2001** [comment]
> > Hello, i'd try to import rdc file but blender messaging me an error ![Знімок екрана (2)](https://user-images.githubusercontent.com/82917218/176971287-90e9ac96-ca4d-46e5-8309-041cc6f1a270.png)
> 
> I've had the same error, tried importing the Cape Town sample and the same error showed up. I used RenderDoc v1.10, MapsModelsImporter-v0.3.3 and the newest Blender, so I'm not sure what the issue is. (The RenderDoc and MapsModelsImporter versions work together, since I used the same versions that a tutorial video suggested. ![image](https://user-images.githubusercontent.com/76436352/209255863-240613d7-08ba-4bad-87be-a57cecc5d74f.png)

![image](https://user-images.githubusercontent.com/76436352/209255958-81176632-b35a-49aa-8a67-38e36bf7d0a1.png)

**Comment by ts3164** [comment]
I also have the same error, did anyone figure it out?

**Comment by ts3164** [comment]
> DROPPING DOWN TO RENDER 1.9 fixed my issue

This works!!!

**Comment by ts3164** [comment]
RenderDoc 1.9 won't work in terms of capturing your own renders. It just won't open but it can be used to open the sample files. Does anyone else have this issue?
