### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x01'.

### ISSUE THREAD

**Issue by glenmarkmartin** [eliemichel/MapsModelsImporter#238]
When importing a capture into Blender, I receive the error above. Verbose log output below.
 - The problematic .rdc file is available via this [link](https://www.dropbox.com/sh/xngafpw73dhznwx/AABS_xEz_ELcYpB7wrZRVuR1a?dl=0).
 - GPU: NVIDIA GeForce RTX 3070
 - MapsModelsImporter v0.5.0
 - RenderDoc v1.19
 - Blender v3.3.0
--------------------------- Log Output -----------------------
```Read prefs: C:\Users\gmmar\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
DEBUG:BlenderGIS-master.core.checkdeps:GDAL Python binding unavailable
DEBUG:BlenderGIS-master.core.checkdeps:PyProj unavailable
DEBUG:BlenderGIS-master.core.checkdeps:Pillow unavailable
DEBUG:BlenderGIS-master.core.checkdeps:ImageIO Freeimage plugin available
addon_utils.disable: MapsModelsImporter not loaded
Modules Installed (MapsModelsImporter) from 'C:\\Users\\gmmar\\Downloads\\MapsModelsImporter-v0.5.0.zip' into 'C:\\Users\\gmmar\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
module changed on disk: 'C:\\Users\\gmmar\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\MapsModelsImporter\\__init__.py' reloading...
Traceback (most recent call last):
  File "C:\Users\gmmar\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\gmmar\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MapsModelsImporter\google_maps.py", line 308, in importCapture
    timer = Timer()
  File "C:\Users\gmmar\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MapsModelsImporter\google_maps.py", line 249, in filesToBlender
    # Get reference matrix
  File "C:\Users\gmmar\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MapsModelsImporter\google_maps.py", line 212, in loadData
     
_pickle.UnpicklingError: invalid load key, '\x01'.```

**Comment by glenmarkmartin** [comment]
Ah, disregard. Simply restarting Blender after swapping out add-in versions did the trick.
