### ISSUE TITLE
Failed to import in Steam-installed Blender

### ISSUE THREAD

**Issue by no1pandeng** [eliemichel/MapsModelsImporter#24]
I saved the rdc file but when I import it from blender there is red texts jumped out.
So I want to ask what went wrong, thanks!

![blender](https://user-images.githubusercontent.com/48761554/74787728-cd8ff080-52a7-11ea-86de-80c6a9f80fb6.png)

Traceback (most recent call last):
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 194, in importCapture
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 42, in captureToFiles
    subprocess.run([python, SCRIPT_PATH, filepath, prefix])
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]  。

location: <unknown location>:-1

**Comment by eliemichel** [comment]
This is an error common to all people using Blender from Steam, because it does not provide python.exe at the same location as a regular install. Could you let me know where python.exe is, either in `D:\Program Files (x86)\Steam\steamapps\common\Blender` or otherwise somewhere else in `D:\Program Files (x86)\Steam\steamapps`?

**Comment by no1pandeng** [comment]
The location is D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\bin
As Steam will automatically create new files for each version of blender.
Tkanks for your responding!

**Comment by eliemichel** [comment]
And where is blender.exe?

**Comment by no1pandeng** [comment]
It is here 
D:\Program Files (x86)\Steam\steamapps\common\Blender

**Comment by eliemichel** [comment]
In a Python console panel inside Blender, can you type this and paste me the output?

```
import sys
print(sys.executable)
print(sys.platform)
```

**Comment by no1pandeng** [comment]
![python console](https://user-images.githubusercontent.com/48761554/74820235-95b19900-52f9-11ea-9a61-621038fed688.png)

**Comment by eliemichel** [comment]
Mmh can you add

```
print([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)])
```

before line 42 of `C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py`

Sorry to ask all this, but I cannot reproduce the error myself.

**Comment by no1pandeng** [comment]
Of course, I have tried but there is nothing actually printed
Here is the output

Traceback (most recent call last):
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 181, in importCapture
    captureToFiles(filepath, prefix)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 42, in captureToFiles
    print([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)]) 
NameError: name 'max_blocks' is not defined

location: <unknown location>:-1

**Comment by eliemichel** [comment]
All right can you do this with the last release? https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc2
There have been quite a change since the v0.1.3 that you are using. ;)

**Comment by no1pandeng** [comment]
Yes, I tried the latest version.

Traceback (most recent call last):
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 195, in importCapture
    captureToFiles(filepath, prefix, max_blocks)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 43, in captureToFiles
    subprocess.run([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)])
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 。

location: <unknown location>:-1

**Comment by eliemichel** [comment]
There should be something printed before the Traceback if you added the "print" at line 42

**Comment by no1pandeng** [comment]
Finally, it shows this

Traceback (most recent call last):
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 181, in importCapture
    addImageMaterial(mat_name, obj, img)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 42, in captureToFiles
    print([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)])
NameError: name 'max_blocks' is not defined

location: <unknown location>:-1

**Comment by no1pandeng** [comment]
I also installed a blender from the web, but it is still not working
but the problems seem different
Traceback (most recent call last):
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 196, in importCapture
    filesToBlender(context, prefix, max_blocks)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 162, in filesToBlender
    uvOffsetScale, matrix, refMatrix = extractUniforms(constants, refMatrix)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 66, in extractUniforms
    uvOffsetScale = globUniforms['webgl_fa7f624db8ab37d1']
KeyError: 'webgl_fa7f624db8ab37d1'

location: <unknown location>:-1

**Comment by eliemichel** [comment]
You're still using v0.1.3 instead of v0.2.0 ;)

**Comment by no1pandeng** [comment]
Sorry, I don't know how to see the version.
In the perferences it shows 0.2.0

Here is the codes it shows 
![blender version](https://user-images.githubusercontent.com/48761554/74844868-05d61400-5326-11ea-9c0d-c8c2d66327ec.png)
Traceback (most recent call last):
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 194, in importCapture
    prefix = makeTmpDir(pref, filepath)
  File "C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 42, in captureToFiles
    print([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)])
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Program Files (x86)\Steam\steamapps\common\Blender\2.82\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]。

location: <unknown location>:-1

**Comment by eliemichel** [comment]
Now it is indeed the v0.2.0 ([this error](https://github.com/eliemichel/MapsModelsImporter/issues/24#issuecomment-588220742) was with v0.1.3 for sure), so let's add again the `print([python, SCRIPT_PATH, filepath, prefix, str(max_blocks)])` before line 42 in `C:\Users\MSI-PC\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py` and to get its output open up the console using "Window > Toggle System Console". There should be a line before the word "Traceback" that is the result of this print statement and that will be halpfull.

In the meantime, could you also provide me with the rdc file you are trying to import?

**Comment by no1pandeng** [comment]
Yes of course.
I just tried and nothing happened, it is because I edited the py file in a wrong way?
![blender 2](https://user-images.githubusercontent.com/48761554/74846269-1c7d6a80-5328-11ea-96d9-9b96093f3655.png)


Here is the link of the cdr file
https://dmail-my.sharepoint.com/:u:/g/personal/dpan_dundee_ac_uk/EZHSv-9u6UZGltxrcYKogFsBs5APbsfbrBO1oTRQ4xAZ9g?e=RzjNIy

**Comment by eliemichel** [comment]
Almost there ^^ Thx for the .rdc
![blender-terminal](https://user-images.githubusercontent.com/5802849/74872496-94b25300-535d-11ea-9b16-341ba9aa3007.png)

**Comment by no1pandeng** [comment]
Oh I see, there is some message in the terminal other than the scripting panel.
Here is what  I got.
['D:\\Program Files (x86)\\Steam\\steamapps\\common\\Blender\\2.80\\python\\bin\\python.exe', 'C:\\Users\\MSI-PC\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons\\MapsModelsImporter\\google_maps_rd.py', 'G:\\Year 5\\Verona\\semester 2\\Capture\\2 18 2.rdc', 'G:\\Year 5\\Verona\\semester 2\\Capture\\2 18 2-x6n4y7p\\2 18 2-', '200']

**Comment by eliemichel** [comment]
Got it! Steam apparently mixes all versions of Blender in the same folder, which confuses the add-on (see how it uses python.exe from 2.80 folder while running script from 2.82). This is fixed, as well as the other issue related to your capture, try RC4! https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc4

**Comment by no1pandeng** [comment]
Thanks so much! It finally worked!
