### ISSUE TITLE
Error when importing RDC files from mapy.cz

### ISSUE THREAD

**Issue by hondzejk** [eliemichel/MapsModelsImporter#264]
Hello, I am unable to import RDC files from mapy.cz, importing from google maps works perfectly

 - The .rdc file https://1drv.ms/u/s!AvDgr7oVm-velvtiiovZlXzTDovW-A?e=wdYgqU
 - NVIDIA GeForce GTX 1650
 - Maps Models Importer v0.6.2
 - RenderDoc 1.25 
 - Blender 3.4.1

Copy from blender info log:

Python: Traceback (most recent call last):
  File "C:\Users\cisar\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\cisar\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps.py", line 372, in importCapture
    filesToBlender(context, prefix, max_blocks)
  File "C:\Users\cisar\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps.py", line 281, in filesToBlender
    uvOffsetScale, matrix, refMatrix = extractUniforms(constants, refMatrix)
  File "C:\Users\cisar\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps.py", line 156, in extractUniforms
    _uParams[2][2] / _uParams[0][2],
ZeroDivisionError: float division by zero

Thanks for the amazing work!

**Comment by Elc3r** [comment]
I have the same problem.

**Comment by VidhosticeSDK** [comment]
Hi,
this works correctly
![image](https://user-images.githubusercontent.com/106232621/229446998-b33f048e-eb94-46ae-bc40-b2287e10b7be.png)

but this cannot be imported
![image](https://user-images.githubusercontent.com/106232621/229447343-b94923b2-8036-4b74-aeb3-dc81a51c9d6c.png)

**Comment by oprinkon** [comment]
Hello, I have the same problem too.

**Comment by LukasLejdar** [comment]
same here. Have any of you managed to make it work in a certain location maybe?

**Comment by NTKKS** [comment]
Gotta share this post with you, seems to work for me as well

Animal Japan reacted: https://napoveda.seznam.cz/forum/threads/answer_reaction_parent/newest/334421
Hello,
I made it work after a long trial and error,
Blender 3.4 , RDC 1.25, a addon Maps Models Importer v0.6.1.

**Comment by kiwioGIT** [comment]
> Gotta share this post with you, seems to work for me as well
> 
> Animal Japan reacted: https://napoveda.seznam.cz/forum/threads/answer_reaction_parent/newest/334421 Hello, I made it work after a long trial and error, Blender 3.4 , RDC 1.25, a addon Maps Models Importer v0.6.1.

that url is no longer avaible, is there anyone that knows what to do?
