### ISSUE TITLE
Getting UnboundLocalError when importing .rdc file into Blender

### ISSUE THREAD

**Issue by AlfonseVanWorden** [eliemichel/MapsModelsImporter#28]
Using version RC4 with Blender 2.82 and RenderDoc 1.6

Getting an error message in Blender after a few seconds:
"
Traceback (most recent call last):
  File "C:\Users\===\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\===\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 210, in importCapture
    filesToBlender(context, prefix, max_blocks)
  File "C:\Users\===\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 176, in filesToBlender
    uvOffsetScale, matrix, refMatrix = extractUniforms(constants, refMatrix)
  File "C:\Users\===\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 83, in extractUniforms
    mdata[0:4],
UnboundLocalError: local variable 'mdata' referenced before assignment

location: <unknown location>:-1
"

Also tried:
making new .rdc files - they seem fine
uninstalling, reinstalling the add-on - tried versions rc4, rc3, rc2

Not sure if this is relevant but my apps are installed to a separate D drive - not sure if perhaps file paths are not an issue.

Would be grateful for guidance! Thanks so much!

**Comment by ayciate** [comment]
Same issue here, my current "workaround" is to recapture but look down more in google maps. Either that's doing something or I'm just getting lucky.

**Comment by eliemichel** [comment]
Please provide a capture file when reporting such an issue!
I've seen this error when people capture from Google Earth instead of Google Maps.

**Comment by AlfonseVanWorden** [comment]
Sorry, first time doing this whole github thing for me -

You are exactly right - Google Maps and not Google Earth was used when I got the error, now everything works perfectly! Thanks so much for the YT tutorial and guide, have been dreaming of a quick and easy way to get those 3d models for a very long time!
