### ISSUE TITLE
KeyError Darwin blender error (MacOS 12.7 on a MacBook Air

### ISSUE THREAD

**Issue by mathflashcards** [eliemichel/MapsModelsImporter#299]
- The .rdc file
CapeTown-RD_1.13.rdc   (the one provided in the samples folder)
 - Your GPU name
 Don't know what you mean if your talking about GPU model then
1.8 GHz Dual-Core Intel Core i5
 - Version of this add-on
 0.6.2
 - Version of RenderDoc
 I didn't use RenderDoc as im on MacOS and i had to use porting kit and got an error cause  
RenderDoc uses MSI blah blah blah...
 - Version of Blender
 3.4

Heres the error if that helps lol:

Python: Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Blender/3.4/scripts/addons/MapsModelsImporter/operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "/Users/username/Library/Application Support/Blender/3.4/scripts/addons/MapsModelsImporter/google_maps.py", line 371, in importCapture
    captureToFiles(context, filepath, prefix, max_blocks)
  File "/Users/username/Library/Application Support/Blender/3.4/scripts/addons/MapsModelsImporter/google_maps.py", line 78, in captureToFiles
    os.environ["PYTHONPATH"] += os.pathsep + os.path.abspath(getBinaryDir())
  File "/Users/username/Library/Application Support/Blender/3.4/scripts/addons/MapsModelsImporter/utils.py", line 38, in getBinaryDir
    platform_dir = {
KeyError: 'Darwin'

**Comment by BLACKFTVV** [comment]
`Python: Traceback (most recent call last):
  File "/Users/blackjac/Library/Application Support/Blender/3.3/scripts/addons/MapsModelsImporter/operators.py", line 54, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "/Users/blackjac/Library/Application Support/Blender/3.3/scripts/addons/MapsModelsImporter/google_maps.py", line 336, in importCapture
    captureToFiles(context, filepath, prefix, max_blocks)
  File "/Users/blackjac/Library/Application Support/Blender/3.3/scripts/addons/MapsModelsImporter/google_maps.py", line 78, in captureToFiles
    os.environ["PYTHONPATH"] += os.pathsep + os.path.abspath(getBinaryDir())
  File "/Users/blackjac/Library/Application Support/Blender/3.3/scripts/addons/MapsModelsImporter/utils.py", line 38, in getBinaryDir
    platform_dir = {
KeyError: 'Darwin'`

me too...
