### ISSUE TITLE
Cannot import Big Ben example in latest release

### ISSUE THREAD

**Issue by Niashi24** [eliemichel/MapsModelsImporter#311]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file: https://github.com/eliemichel/MapsModelsImporter-samples/blob/master/samples/bigben-RD_1.25.rdc
 - Your GPU name: Intel(R) Iris(R) Xe Graphics
 - Version of this add-on: 0.6.2
 - Version of RenderDoc: 1.25
 - Version of Blender: 3.4.0

Debug output:
```
google_maps_rd failed and returned:
Loading capture from C:\Users\<user>\Downloads\RenderDoc_1.25_64\Captures\bigben-RD_1.25.rdc...
Couldn't open file: File is corrupted: Invalid capture file. Expected magic 434f4452, got 6170227b.
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 347, in <module>
    main(controller)
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 339, in main
    scraper.run()
  File "C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 244, in run
    drawcalls = self.consolidateEvents(controller.GetRootActions())
AttributeError: 'NoneType' object has no attribute 'GetRootActions'
```

**Comment by eliemichel** [comment]
> Couldn't open file: File is corrupted: Invalid capture file. Expected magic 434f4452, got 6170227b.

Try re-downloading bigben-RD_1.25.rdc

**Comment by 3dimka** [comment]
Hmm.. 
I'm seeing the same error  while trying to import the big ben sample file:

AttributeError: 'NoneType' object has no attribute 'GetRootActions'

==========================================================================================
google_maps_rd failed and returned:
Loading capture from S:\Shared\bigben-RD_1.25.rdc...
Couldn't open file: File format is unrecognised: Unrecognised file type. File magic number is 0a0a0a0a.
Traceback (most recent call last):
  File "C:\Users\3dimk.DESKTOP-5I9A7PI\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 377, in <module>
    main(controller)
  File "C:\Users\3dimk.DESKTOP-5I9A7PI\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 369, in main
    scraper.run()
  File "C:\Users\3dimk.DESKTOP-5I9A7PI\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 274, in run
    drawcalls = self.consolidateEvents(controller.GetRootActions())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'GetRootActions'


Extra info:
 - python = D:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin\python.exe
 - python_home = D:\Program Files\Blender Foundation\Blender 4.1\4.1\python
