### ISSUE TITLE
can't import any RDC, sample or otherwise in MMI v0.6.2

### ISSUE THREAD

**Issue by sunflowers33d** [eliemichel/MapsModelsImporter#312]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file (bigben-RD_1.25.rdc)
 - Your GPU name (NVIDIA GeForce RTX 3060 Laptop GPU)
 - Version of this add-on (Maps Models Importer v0.6.2)
 - Version of RenderDoc (RenderDoc 1.25)
 - Version of Blender (Blender 3.4)

RDCs I make also do not work. 

``Python: --- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\logging\handlers.py", line 74, in emit
    self.doRollover()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\logging\handlers.py", line 431, in doRollover
    dfn = self.rotation_filename(self.baseFilename + "." +
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\logging\handlers.py", line 95, in rotation_filename
    result = self.namer(default_name)
  File "C:\Users\bababa\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AliceLG\__init__.py", line 91, in logfile_namer
    base_filename, ext, date = default_name.split(".")
ValueError: too many values to unpack (expected 3)
Call stack:
  File "C:\Users\bababa\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\AliceLG\__init__.py", line 81, in log_exhook
    LookingGlassAddonLogger.critical("An unhandled error occured. Here is the traceback:\n", exc_info=(exc_type, exc_value, exc_traceback))
Message: 'An unhandled error occured. Here is the traceback:\n'
Arguments: ()
``

**Comment by sunflowers33d** [comment]
oddly enough both the BigBen sample and the RDC i tried making import into blender 3.4 without any problems using mapsmodelimporter v0.6.0, so i'm not sure what that's about. i'll stick with v0.6.0 for the time being but still may be worth looking into
