### ISSUE TITLE
Cannot Import Latest Samples

### ISSUE THREAD

**Issue by DiBop** [eliemichel/MapsModelsImporter#314]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
[venise-RD_1.31](https://github.com/eliemichel/MapsModelsImporter-samples/blob/master/samples/venise-RD_1.31.rdc)

 - Your GPU name
NVIDIA GeForce RTX 3060 Laptop GPU

 - Version of this add-on
v0.7.0

 - Version of RenderDoc
v1.31

 - Version of Blender
 v4.1

At first I _was_ getting this error

```Python: Traceback (most recent call last):
Python: Traceback (most recent call last):
  File "C:\Users\MYCOM\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\operators.py", line 60, in execute
    importCapture(context, self.filepath, self.max_blocks, self.use_experimental, pref)
  File "C:\Users\MYCOM\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps.py", line 373, in importCapture
    filesToBlender(context, prefix, max_blocks, use_experimental)
  File "C:\Users\MYCOM\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps.py", line 347, in filesToBlender
    obj.matrix_world = matrix * globalScale
    ^^^^^^^^^^^^^^^^
ReferenceError: StructRNA of type Object has been removed


```

I then tried to load in a 1.25 sample model (BigBen) just to see and now I get this error when I try the Venice sample.
```
==========================================================================================
google_maps_rd failed and returned:
Loading capture from D:\[3D PROJECTS]\[360]\INNOVA\RenderDoc\venise-RD_1.31.rdc...
Couldn't open file: File format is unrecognised: Unrecognised file type. File magic number is 0a0a0a0a.
Traceback (most recent call last):
  File "C:\Users\MYCOM\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 377, in <module>
    main(controller)
  File "C:\Users\MYCOM\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 369, in main
    scraper.run()
  File "C:\Users\MYCOM\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 274, in run
    drawcalls = self.consolidateEvents(controller.GetRootActions())
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'GetRootActions'


Extra info:
 - python = C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin\python.exe
 - python_home = C:\Program Files\Blender Foundation\Blender 4.1\4.1\python
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this Add-on
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version = 1.10 for MapsModelsImporter >= 0.3.3 and <= 0.3.7
   - RenderDoc Version 1.13 - 1.14 for MapsModelsImporter >= 0.4.0  and <= 0.4.2
   - RenderDoc Version = 1.19 for MapsModelsImporter >= 0.5.0
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading.
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output
```

What is really odd, at least to me, is that when I try to import my first capture it loads the model but it is all jacked-up:
![2024-04-11_19-10-57](https://github.com/eliemichel/MapsModelsImporter/assets/479367/610c7e30-11b4-4d4e-9cb3-fb047964f826)

But when I load subsequent captures I am getting the "Please make sure that..." error message.

Let me know if you need any additional info!

**Comment by eliemichel** [comment]
> Couldn't open file: File format is unrecognised: Unrecognised file type. File magic number is 0a0a0a0a.

For some reason the file is not recognized, maybe [venise-RD_1.31](https://github.com/eliemichel/MapsModelsImporter-samples/blob/master/samples/venise-RD_1.31.rdc) was nto correctly downloaded (it happens with large files on GitHub)

The problem with you own captures may be different, could you share one? Also you may try the fix suggested in #317
