### ISSUE TITLE
Custom captures are not importing.

### ISSUE THREAD

**Issue by frezap** [eliemichel/MapsModelsImporter#317]
The venice sample imports fine.

 - The .rdc file: https://file.io/pE4ZnO8QY2Im
 - Your GPU: Nvidia GTX
 - Version of this add-on: 0.7.0
 - Version of RenderDoc: 1.31
 - Version of Blender: 4.1

Logs:

`google_maps_rd failed and returned:
Loading capture from ...rdctest.rdc...
Trying scraping strategy #4 (from draw call #0)...
(Skipping drawcall ClearDepthStencilView())
(Skipping drawcall ClearView())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
Not relevant yet: ClearRenderTargetView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: DiscardView()
Not relevant yet: DiscardView()
Not relevant yet: ClearRenderTargetView()
Not relevant yet: DrawInstanced()
Not relevant yet: DrawInstanced()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: DrawInstanced()
Not relevant yet: DrawInstanced()
Traceback (most recent call last):
  File "...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 377, in <module>
    main(controller)
  File "...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 369, in main
    scraper.run()
  File "...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 278, in run
    relevant_drawcalls, capture_type = self.extractRelevantCalls(drawcalls)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 214, in extractRelevantCalls
    return self.extractRelevantCalls(drawcalls, _strategy=_strategy+1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 176, in extractRelevantCalls
    if not skipped_drawcalls or self.hasUniform(skipped_drawcalls[0], "_uMeshToWorldMatrix"):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 142, in hasUniform
    constants = self.getVertexShaderConstants(draw)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 132, in getVertexShaderConstants
    elif var.type == rd.VarType.Int:
                     ^^^^^^^^^^^^^^
  File "...Blender Foundation\Blender 4.1\4.1\python\Lib\enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: Int. Did you mean: 'SInt'?`

**Comment by eliemichel** [comment]
This was a bug indeed, thanks for sharing the rdc file! You may replace your `...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py` file with this new one: [`google_maps_rd.py`](https://github.com/eliemichel/MapsModelsImporter/blob/70fca735bd42b1785356622a07e13c2604ff9af1/blender/MapsModelsImporter/google_maps_rd.py), let me know if it works I'll make a new release!

![image](https://github.com/eliemichel/MapsModelsImporter/assets/5802849/8bb96443-8057-403d-9c97-b29a9a43e733)

**Comment by CL-matt** [comment]
> This was a bug indeed, thanks for sharing the rdc file! You may replace your `...AppData\Blender\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py` file with this new one: [`google_maps_rd.py`](https://github.com/eliemichel/MapsModelsImporter/blob/70fca735bd42b1785356622a07e13c2604ff9af1/blender/MapsModelsImporter/google_maps_rd.py), let me know if it works I'll make a new release!
> 
> ![image](https://private-user-images.githubusercontent.com/5802849/324256647-8bb96443-8057-403d-9c97-b29a9a43e733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODUxMzMsIm5iZiI6MTcxMzc4NDgzMywicGF0aCI6Ii81ODAyODQ5LzMyNDI1NjY0Ny04YmI5NjQ0My04MDU3LTQwM2QtOWM5Ny1iMjlhOWE0M2U3MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTEyMDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNiZjliMDJlNmU4MTVhMGY3ZTczZjg5Zjc4NDdmOWJlMDRlYjExNWU3ODliMWY4Zjk0MTA2NDMzM2M5Yjg5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XyNxLO-Hgr-sVh4O9bSpTTglJSM75cWvjN1MQaubn0k)

After the google_maps_rd_py had been replaced to the new one, it works. But there is a new problem... The model is incomplete.
My device:
The rdc file: https://file.io/U5z4ypR2w3lD
Your GPU: Nvidia GTX 4060
Version of this add-on: 0.7.0
Version of RenderDoc: 1.31
Version of Blender: 4.1
Screenshot in Blender:
![imagen](https://github.com/eliemichel/MapsModelsImporter/assets/84998576/d0e45a77-3595-4afe-9bc5-2814f94c5eda)
Screenshot RenderDoc:
![imagen](https://github.com/eliemichel/MapsModelsImporter/assets/84998576/ef2cb6e2-5089-4582-b487-76ebac4dcce4)

**Comment by frezap** [comment]
Importing custom captures works now on my end. Thank you!
