### ISSUE TITLE
Cannot import RDC file into Blender

### ISSUE THREAD

**Issue by mbot3030** [eliemichel/MapsModelsImporter#320]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file (it wont let me upload the file)
 - Nvidia GeForceRTX 3080 Ti
 - Map Models Importer 0.7
 - Blender 4.1
 -Render Doc 1.31

This is what I'm seeing in the System Console.  Anything I try to import from stuff Im trying to capture, I see the same thing.  The Venice sample works. 

google_maps_rd failed and returned:
Loading capture from E:\Google_earth_01\SFO\sfo_02.rdc...
Trying scraping strategy #4 (from draw call #0)...
(Skipping drawcall ClearDepthStencilView())
(Skipping drawcall ClearRenderTargetView())
(Skipping drawcall ClearDepthStencilView())
(Skipping drawcall ClearRenderTargetView())
Not relevant yet: ClearRenderTargetView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearRenderTargetView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearRenderTargetView()
Not relevant yet: ClearDepthStencilView()
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 377, in <module>
    main(controller)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 369, in main
    scraper.run()
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 278, in run
    relevant_drawcalls, capture_type = self.extractRelevantCalls(drawcalls)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 214, in extractRelevantCalls
    return self.extractRelevantCalls(drawcalls, _strategy=_strategy+1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 176, in extractRelevantCalls
    if not skipped_drawcalls or self.hasUniform(skipped_drawcalls[0], "_uMeshToWorldMatrix"):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 142, in hasUniform
    constants = self.getVertexShaderConstants(draw)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 123, in getVertexShaderConstants
    elif member.type == rd.VarType.Int:
                        ^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: Int. Did you mean: 'SInt'?

**Comment by xavier114** [comment]
Same here
