### ISSUE TITLE
"local variable 'mdata' referenced before assignment" in Blender when trying to import RDC file

### ISSUE THREAD

**Issue by molton** [eliemichel/MapsModelsImporter#36]
My GPU is the Radeon rx580
Maps Models Importer version 0.2.1
RenderDoc 1.6
Blender 2.82

Hello, thanks for making this excellent project, I very much look forward to being able to get it to work.  I just installed a fresh copy of Windows, got the latest Chrome.  I noticed in the tutorial video the API he's using says OpenGLES, I cannot get that to work, but reading the github it doesn't really mention a specific API,  My computer wants to use D3D11, which causes issues for the print screen button, so I would just use the "capture after so many seconds" option and go back to chrome and waive the view around, which seems to work, it gets the 3d texture data and something shows up under the mesh view.  But when I try to import in blender it does not work, I get this error.

Unfortunately the rdc file is too big to upload here, but here's a link 
https://www.dropbox.com/s/5kkj9yrvgixvre9/RDCfromRenderDoc.zip?dl=0

Traceback (most recent call last):
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 210, in importCapture
    filesToBlender(context, prefix, max_blocks)
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 176, in filesToBlender
    uvOffsetScale, matrix, refMatrix = extractUniforms(constants, refMatrix)
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 83, in extractUniforms
    mdata[0:4],
UnboundLocalError: local variable 'mdata' referenced before assignment

location: <unknown location>:-1
[rdc file.txt](https://github.com/eliemichel/MapsModelsImporter/files/4284039/rdc.file.txt)

**Comment by molton** [comment]
tried some of the older relese candidates and I get these KeyError: 'webgl_fa7f624db8ab37d1' errors, is this because the AMD cards are not supported?  I'm going to try the older versions as well, I figured I'd share what I found

 Traceback (most recent call last):
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 195, in importCapture
    filesToBlender(context, prefix, max_blocks)
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 161, in filesToBlender
    uvOffsetScale, matrix, refMatrix = extractUniforms(constants, refMatrix)
  File "C:\Users\mike3\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 65, in extractUniforms
    uvOffsetScale = globUniforms['webgl_fa7f624db8ab37d1']
KeyError: 'webgl_fa7f624db8ab37d1'

location: <unknown location>:-1

**Comment by eliemichel** [comment]
This is a capture of Google Earth, while the add-on is for Google **Maps**. ;)
