### ISSUE TITLE
cant import the .rdc into blender 2.82

### ISSUE THREAD

**Issue by Jasper1298** [eliemichel/MapsModelsImporter#37]
Hi, im trying to import the .rdc intro blender 2.8 but im getting an error.
I used RenderDoc v1.6 to do the capture and it worked, but when i save the capture and import that into blender (with Maps Models Importer v0.2.0 RC1) i get the following error:

Traceback (most recent call last):
  File "C:\Users\jaspe\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\jaspe\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 174, in importCapture
    continue
  File "C:\Users\jaspe\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 41, in captureToFiles
    python = os.path.join(python_home, "bin", "python.exe" if sys.platform == "win32" else "python3.7m") # warning: hardcoded python version for non-windows might fail with Blender update
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

Also, when i save the capture it creates 3 empty folder on my desktop... not 1 folder with actual files in it, like in the video (see attachment). Anyone has the same error or know how to fix it??

<img width="953" alt="Screenshot (117)" src="https://user-images.githubusercontent.com/60921416/76009732-f81db280-5f11-11ea-8cf9-1e32751c135c.png">
 
dont think this is actually necessary but just incase, here are some pc specs:
i7-4790k 
gtx 960 4gb
16gb ram

**Comment by Jasper1298** [comment]
i used RenderDoc v1.5 instead and it worked. idk what is wrong with v.16 but that version seems to work for every except me but i got it done now with v1.5

**Comment by eliemichel** [comment]
Last version of the add-on is v0.2.1, quite changed since v0.2.0 RC1
