### ISSUE TITLE
Issue when importing rdc file 

### ISSUE THREAD

**Issue by Fqlox** [eliemichel/MapsModelsImporter#46]
Hello,

First of all, congrats on the Addons, it is awesome.

I managed to make one .rdc file work following this tutorial: https://www.youtube.com/watch?v=F_XsmoZJmG8
But the import worked just once. 
I get this error when importing another rdc file:

```
Traceback (most recent call last):
  File "C:\Users\felix\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\felix\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 210, in importCapture
    filesToBlender(context, prefix, max_blocks)
  File "C:\Users\felix\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 170, in filesToBlender
    indices, positions, uvs, img, constants = loadData(prefix, drawcallId)
  File "C:\Users\felix\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 142, in loadData
    img = bpy.data.images.load("{}{:05d}-texture.png".format(prefix, drawcallId))
RuntimeError: Error: Cannot read 'D:\users\Felix\Documents\DSAA2\googlemaps\caca-xj9r29i\caca-00000-texture.png': No such file or directory


location: <unknown location>:-1
```

For futher information: 
- GPU: RTX 2070  
- RenderDoc v1.7
- Blender 2.82
- RDC file: http://felixjely.fr/projet/error/Error_file.zip

Thanks in advance,

Felox

**Comment by eliemichel** [comment]
You must move in the 3D view while taking the capture, otherwise there is no 3D data in it because Google Maps just reuses the previous frame (to save computing resources)! ;)
