### ISSUE TITLE
Issue: Cannot import RDC file

### ISSUE THREAD

**Issue by Quinity** [eliemichel/MapsModelsImporter#49]
I'm having a problem. [Google Translation]

I succeeded in capturing the rdc file, but I can't get it from the blender. I saved 7 .rdc files and the first file 'hakodate' failed to import when [invalid RDC capture file...] came up. In the 2nd and 7th attempts, attempts to import will delay for approximately 0.1 second, but nothing will happen and no error message will occur.  

I attach the .rdc file to my Google drive.
(https://drive.google.com/drive/folders/1_8RSQ9NkKtlPi2TDmJ6Zag3_KceE1qo5?usp=sharing)

The reason I'm guessing right now is that the capture was not done properly. [In ÉLie Michel's video](https://youtu.be/X6Q7dbtXVZQ?t=217), you can see a number of glDrawElements in the Color Pass #2 of the Event Browser in renderdoc. On the other hand, I only have one glDrawElement on Colour Pass #2, and this is what it looks like when I check it with a texture viewer.
![fsfsf](https://user-images.githubusercontent.com/63095044/78390744-0c8fc080-7620-11ea-9052-b9950bf9758f.PNG)
I feel like the capture is done before moving the Google Map screen by clicking the capture button and capturing it in a second.)

( Blender-2.82 / Vivaldi-1.12.955.42 / renderdoc-1.6 / MapsModelsImporter-0.2.2 / gtx1060 /)

**Comment by Manaland2020** [comment]
Did you tried a capture with delay? For myself, I set it to 5 seconds. Enough time to actually go into the chrome browser and move the map a little bit. I think that the movement is needed in order to get data into renderdoc. I came from this video here and followed all steps, using version Blender 2.82a, Renderdoc v1.7 and current mapsmodelsimporter. Works pretty good for me.

Little side-notes and tips:

- For best quality, I've set my Monitor (currently just a 1080p) to 4K through NVidia upscaling.
- Using a Chrome plugin to resize my Chrome window to a certain fixed size (in my case I used 2100x2100)
- Set Chrome zoom page to 25% for highest quality at highest zoomlevel. I figured that i can scroll with my middlemousebutton two times out (Razer mouse but others might work the same) without any change in LOD. Third time = lower tex res + lower level of detail.
- The capture from it is like ~350 MB big then.
- The import took one hour on an Ryzen5 3600 and 16gb DDR4, GTX1080.
- As a general thumb-rule I figured that a 60MB file has like 600-700 meshes, 120M file double and so on.
- I just set my Blocks on import to 15000 just to be safe and for now all capture imports went fine, just needed time. You can actually watch a movie or netflix, BUT DONT TOUCH BLENDER :D

https://www.youtube.com/watch?v=F_XsmoZJmG8

Tell me if it worked. :3

**Comment by eliemichel** [comment]
Hi @Quinity it seems that your browser was using OpenGL when rendering while with the new chrome flags it should be using DirectX 11. Did you ensure that you started chrome with this shortcut:

    C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"

**Comment by Quinity** [comment]
Oh! Thank you for your answer.
I'm currently using Vivaldi-1.12.955.42 (I couldn't run Chrome Debug Mode).

First, I deleted Renderdoc 1.6, downloaded 1.7, and reinstalled Add-on. And I set Capture after delay from 0 to 5.
The results were different. Although the 3D model was still not imported, an error message is now output.
![Capture](https://user-images.githubusercontent.com/63095044/78420359-40eb9700-7689-11ea-85a7-3ad613bce66e.jpg)
The system console is also updated. The contents are as follows.
> 
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 186, in <module>
    main(controller)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 168, in main
    texture_bind = bindpoints.samplers[-1].bind
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 186, in <module>
    main(controller)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 168, in main
    texture_bind = bindpoints.samplers[-1].bind
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 186, in <module>
    main(controller)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 168, in main
    texture_bind = bindpoints.samplers[-1].bind
IndexError: list index out of range

> 
I tried to capture and bring it to the blender six times, but the results were all the same....

**Comment by Quinity** [comment]
> 안녕하세요 @Quinity 새로운 크롬 플래그로 렌더링 할 때 브라우저가 OpenGL을 사용하고있는 것으로 보입니다. DirectX 11을 사용해야합니다.이 단축키로 크롬을 시작했는지 확인 했습니까?
> 
> ```
> C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"
> ```
> 
> 또한 @ Manaland2020에서 알 수 있듯이 "지연 후 캡처"기능을 사용하여 캡처 할 때 3D보기로 이동하고 있는지 확인할 수 있습니다. 이는 대부분의 캡처에는 해당되지 않는 것 같습니다. 또한 캡처하기 전에 Google지도에서 3D 모드를 사용하도록 설정했는지 확인하십시오 (예 : Ctrl + 마우스를 왼쪽으로 드래그하여 드래그).

---------------------------------------------------------------------------------------------
Problem solved! It was a problem with using the vivaldi browser.
At first I tried to change Chrome's target URL, but the vaccine program blocked it. So I was using the vivaldi browser. While trying many ways to solve the problem, I tried on another computer, and when I saw it being captured normally, I was able to remove the vaccine program and use chrome to solve it.

**Comment by Quinity** [comment]
> [](https://www.youtube.com/watch?v=F_XsmoZJmG8)
> 
> .. 버전 Blender 2.82a, Renderdoc v1.7 및 현재 mapsmodelsimporter를 사용하여 모든 단계를 수행했습니다. 꽤 잘 작동합니다.
> (중요 : 블렌더-GIS 참조 맵 스케일을 비디오에서 신뢰하지 마십시오. 저에게는 50이 아니라 12.1이므로 실제 줌 레벨에 크게 의존한다고 생각합니다. 아마도 아직 테스트하지 않았습니다)

Thank you. @Manaland2020! 

> 지연된 캡처를 시도 했습니까? 나 자신을 위해 5 초로 설정했습니다. 실제로 크롬 브라우저로 이동하여지도를 약간 이동할 시간이 충분합니다. 데이터를 renderdoc로 가져 오기 위해서는 움직임이 필요하다고 생각합니다. 이 비디오에서 왔어요 ..
> 
> https://www.youtube.com/watch?v=F_XsmoZJmG8
> 
> .. 버전 Blender 2.82a, Renderdoc v1.7 및 현재 mapsmodelsimporter를 사용하여 모든 단계를 수행했습니다. 꽤 잘 작동합니다.
> (중요 : 블렌더-GIS 참조 맵 스케일을 비디오에서 신뢰하지 마십시오. 저에게는 50이 아니라 12.1이므로 실제 줌 레벨에 크게 의존한다고 생각합니다. 아마도 아직 테스트하지 않았습니다)
> 
> 작은 참고 사항 및 팁 :
> 
> * 최상의 품질을 위해 NVidia 업 스케일링을 통해 모니터 (현재 1080p)를 4K로 설정했습니다.
> * Chrome 플러그인을 사용하여 Chrome 창의 크기를 특정 고정 크기로 조정합니다 (제 경우에는 2100x2100을 사용했습니다)
> * 가장 높은 줌 레벨에서보기 공간이 많으면서 최상의 품질을 얻으려면 Chrome 줌 페이지를 25 %로 설정하십시오. LOD를 변경하지 않고 마우스 가운데 버튼으로 두 번 스크롤 할 수 있다고 생각했습니다 (Razer 마우스이지만 다른 기능은 동일하게 작동 할 수 있음). 세 번째 시간 = 낮은 텍스 해상도 + 낮은 세부 수준.
> * 그것의 캡처는 그때 ~ 350MB 큰 것입니다.
> * Ryzen5 3600 및 16gb DDR4, GTX1080에서 가져 오는 데 1 시간이 걸렸습니다.
> * 일반적으로 60MB 파일에는 600-700 메쉬, 120M 파일 이중 등이 있다고 생각했습니다.
> * 안전을 위해 가져 오기시 블록을 15000으로 설정했으며 지금은 모든 캡처 가져 오기가 정상적으로 진행되었습니다. 당신은 실제로 영화 나 넷플릭스를 볼 수 있습니다.
> 
> 그것이 효과가 있었다면, 행운을 빕니다! :삼



> Did you tried a capture with delay? For myself, I set it to 5 seconds. Enough time to actually go into the chrome browser and move the map a little bit. I think that the movement is needed in order to get data into renderdoc. I came from this video here..
> 
> https://www.youtube.com/watch?v=F_XsmoZJmG8
> 
> ..and followed all steps, using version Blender 2.82a, Renderdoc v1.7 and current mapsmodelsimporter. Works pretty good for me.
> (Important: Don't trust the Blender to GIS reference mapscale in the video. For me it was not scale of 50 but 12.1 so I think it highly depends on actual zoom levels as well..maybe, did not tested it yet)
> 
> Little side-notes and tips:
> 
> * For best quality, I've set my Monitor (currently just a 1080p) to 4K through NVidia upscaling.
> * Using a Chrome plugin to resize my Chrome window to a certain fixed size (in my case I used 2100x2100)
> * Set Chrome zoom page to 25% for highest quality with a lot of view-space at highest zoomlevel. I figured that i can scroll with my middlemousebutton two times out (Razer mouse but others might work the same) without any change in LOD. Third time = lower tex res + lower level of detail.
> * The capture from it is like ~350 MB big then.
> * The import took one hour on an Ryzen5 3600 and 16gb DDR4, GTX1080.
> * As a general thumb-rule I figured that a 60MB file has like 600-700 meshes, 120M file double and so on.
> * I just set my Blocks on import to 15000 just to be safe and for now all capture imports went fine, just needed time. You can actually watch a movie or netflix, BUT DONT TOUCH BLENDER :D
> 
> Tell me if it worked, good luck! :3

Thank you. @Manaland2020!
I think your tip will be very helpful. But I can't understand because I use a translator... 
If you don't mind, could you record the process of referring to the tip on a screen recorder program like 'NVIDIA SHADOWPLAY' and send it to trewsd5724@gmail.com?  Of course, thank you very much for your kind reply even if you didn't go that far.
