### ISSUE TITLE
Import Failing

### ISSUE THREAD

**Issue by eblabs** [eliemichel/MapsModelsImporter#50]
Hi,

Thanks for all your hard work on this toolset!

Im running into this problem. Have you seen this before?

Thanks again for your help!!

`
reloading addon: MapsModelsImporter 1561873110.0805633 1587223563.316709 'C:\\Users\\eric\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\MapsModelsImporter\\__init__.py'
Modules Installed () from 'C:\\Users\\eric\\Downloads\\MapsModelsImporter-v0.2.2.zip' into 'C:\\Users\\eric\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 32, in <module>
    _, CAPTURE_FILE, FILEPREFIX, MAX_BLOCKS_STR = sys.argv[:4]
ValueError: not enough values to unpack (expected 4, got 3)
Traceback (most recent call last):
  File "C:\Users\eric\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 32, in <module>
    _, CAPTURE_FILE, FILEPREFIX, MAX_BLOCKS_STR = sys.argv[:4]
ValueError: not enough values to unpack (expected 4, got 3)
`

 - RTX 2080
 - Maps Models Importer v0.2.2
 - Version of RenderDoc (1.7 recommended)
 - Version of Blender (2.82 recommended)

**Comment by eblabs** [comment]
Here is a link to one of the files:
https://gofile.io/?c=AedPVA

**Comment by eblabs** [comment]
Ah, I found part of the issue. I was using Google Earth, not Google Maps. 

I think I figured it out, with the D3D11 set, google maps wasnt showing the 3D display option. I was able to enable it by using a url from another browser where it WAS enabled. Now its working.
