### ISSUE TITLE
StructRNA error when importing with Blender 2.90

### ISSUE THREAD

**Issue by Freznosis** [eliemichel/MapsModelsImporter#78]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - [The .rdc file](https://drive.google.com/file/d/1Mg4rY3PE2ohCYhknXroyzCYJBt2DfTXr/view?usp=sharing)
 - GTX 1080Ti
 - MMI 1.3
 - RenderDoc 1.8
 - Blender 2.90

Here is the error.

> Traceback (most recent call last):
>   File "C:\Users\Freznosis\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\operators.py", line 54, in execute
>     importCapture(context, self.filepath, self.max_blocks, pref)
>   File "C:\Users\Freznosis\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps.py", line 222, in importCapture
>     if constants["DrawCall"]["topology"] == 'TRIANGLE_STRIP':
>   File "C:\Users\Freznosis\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\MapsModelsImporter\google_maps.py", line 202, in filesToBlender
>     drawcall_id = 0
> ReferenceError: StructRNA of type Object has been removed
> 
> location: <unknown location>:-1

Worked fine on Blender 2.8, after upgrading to 2.9 it seems to not work anymore. Reinstalled the plugin and blender, no dice.

**Comment by eliemichel** [comment]
I was able to open it with 2.90:

![jp](https://user-images.githubusercontent.com/5802849/93015406-88bc0600-f5b9-11ea-8c78-4db6c26d61fa.png)

Could you turn extra debug info on in the addon's preferences and copy the full text log in the system consol (Window > Toggle System Console)?

**Comment by eliemichel** [comment]
Hi @Freznosis, do you still have this issue with the new 2.91 version of Blender? (using RenderDoc **1.10** and this addon's **0.3.5**)

**Comment by Freznosis** [comment]
> Hi @Freznosis, do you still have this issue with the new 2.91 version of Blender? (using RenderDoc **1.10** and this addon's **0.3.5**)

Hi @eliemichel ,

I did a clean Blender install and clean RenderDoc install, then installed MMI latest. 

Same error unfortunately. Do you think there is a certain Blender or OS (W10) setting that might cause some kind of rear/write error? Here is the full [error-capture.log](https://github.com/eliemichel/MapsModelsImporter/files/5689182/error-capture.log)
